services:
  - type: web
    name: sweet-shop-api
    env: node
    plan: free
    rootDir: apps/api
    buildCommand: pnpm install --no-frozen-lockfile && pnpm --filter shared build && pnpm prisma generate --schema=./prisma/schema.prisma && pnpm build && pnpm migrate:deploy && pnpm prisma seed --schema=./prisma/schema.prisma
    startCommand: pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: sweet-shop-db
          property: connectionString
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: PORT
        value: 10000

databases:
  - name: sweet-shop-db
    databaseName: sweetshop
    user: sweetshop_user
    plan: free
